web:
    build: .
    command: python -u run.py
    ports:
      - "5000:5000"
    volumes:
      - .:/workit
    links:
      - db
db:
    image: mongo:3.4
    container_name: 'mongo-container'
    environment: 
      - MONGO_INIT_DATABASE=workit
      - MONGO_INIT_ROOT_USERNAME=admin
      - MONGO_INIT_ROOT_PASSWORD=admin
    